### ISSUE TITLE
[C4GT Community]: Do not show metadata on Splash if it does not exist in db

### ISSUE THREAD

**Issue by suryabulusu** [avantifellows/quiz-frontend#158]
## Description
For example, if gradekey is not there in quiz retrieved from db, do not show Class in Splash.

Example of error case 

## Goals
- [ ] Check all information in splash
- [ ] If any info is not available from backend, display a default value.

### Expected Outcome

Splash component is not empty

### Implementation Details

See Splash.vue

### Mockups/Wireframes

![image](https://github.com/avantifellows/quiz-frontend/assets/21237473/0f6eb920-e21e-44ec-aee5-c7ee98b22e76)

### Product Name

Quiz Frontend

### Organisation Name

Avanti Fellows

### Domain

Education

### Tech Skills Needed

Vue.js

### Mentor(s)

@suryabulusu 

### Complexity

Low

### Category

Frontend

**Comment by kesharibhai84** [comment]
hi @suryabulusu , please assign me this issue i want to work resolve this

**Comment by neeraj542** [comment]
I want to work on this issue under Augtoberfest, C4GT.
Please assign this issue to me if possible.

**Comment by VedantKhairnar** [comment]
Hey @kesharibhai84,
Do you need any assistance in implementing the requirement.
Feel free to let us know.
Thanks.

**Comment by VedantKhairnar** [comment]
Hey @neeraj542,
Will you pls share your approach? This will help Surya in assigning the issue.
If Keshari is unavailable, Surya will assign it to you.
Thanks.

**Comment by kesharibhai84** [comment]
Hey @neeraj542,
Actually I got stuck in some academic projects stuff .
Today I just started working on it , will let u know if I need any assistance.
Thanks

**Comment by VedantKhairnar** [comment]
Hello @kesharibhai84 
How's it going on this issue?
Anywhere we can help?

Thanks.

**Comment by kesharibhai84** [comment]
Hey @VedantKhairnar  iwas busy with the other issue on the project which got merged few days back only.
If anybody is interested please assign them as I can start it after 1 sept only

**Comment by VedantKhairnar** [comment]
You may continue working on this @kesharibhai84 from Sept 1.
We will still consider it for augtoberfest.
Thanks.

**Comment by Sudhish23** [comment]
To solve this issue, I have applied conditional rendering using Vue.js's v-if directive. The problem was that the "Class" information was being displayed even when the grade field was missing. To address this:

I wrapped the "Class" field display inside a v-if="grade" condition.
This ensures that the "Class" field is only rendered when the grade data is available from the backend.
If grade is missing, the field will be hidden, preventing empty or misleading information from appearing in the UI.                                     By using above approach I have tried to solve the issue. If it is correct Can I raise a Pull Request.

**Comment by suryabulusu** [comment]
hey @Sudhish23 you may raise a PR

**Comment by Asp-Codes** [comment]
hey @suryabulusu could you share the API key ("Please contact the repository developers for {apiKey}"). for testing the code!

**Comment by jaanbaaz** [comment]
hi
